[tool.poetry]
name = "tctwrap"
version = "0.3.1"
description = "Python TCT Wrapper"
authors = ["Shoma Matsui <matsui@shoma.cc>", "Masahiro Konishi <konikoni428@gmail.com>"]
license = "Apache-2.0"
build = "build.py"

[tool.poetry.dependencies]
python = "^3.7"
u-msgpack-python = "^2.7.1"
graphviz = "^0.16"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
flake8 = "^3.9.2"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"