[tool.poetry]
name = "PyTCT"
version = "0.0.0"
description = "Python TCT Library"
authors = ["Shoma Matsui <matsui@shoma.cc>", "Masahiro Konishi <konikoni428@gmail.com>"]
license = "Apache-2.0"
build = "build.py"
include = [
    { path = "libtct", format = "sdist" },
]

[tool.poetry.dependencies]
python = "^3.7"
u-msgpack-python = "^2.7.1"
graphviz = "^0.16"
typing-extensions = ">=4.1.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"

[build-system]
requires = ["poetry_core>=1.0.0", "setuptools", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"