# This is a basic workflow to help you get started with Actions
name: Build PyTCT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ['3.7', '3.8', '3.9', '3.10']


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: ${{matrix.python}}
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          
      - name: Build
        run: |
          poetry build
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: PyTCT
          path: dist
          retention-days: 7
