# This is a basic workflow to help you get started with Actions
name: Build PyTCT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Python
        uses: actions/setup-python@v4
        if: runner.os == 'macOS'
        with:
          python-version: '3.x'
      
      - name: Build
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_ARCHS_LINUX: "auto64 aarch64"
          CIBW_ARCHS_MACOS: "universal2"
          CIBW_ARCHS_WINDOWS: "auto64"
          CIBW_SKIP: "pp*-manylinux_aarch64 cp*-musllinux*"
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: PyTCT
          path: ./wheelhouse/*.whl
          retention-days: 7